- src/app/layout.tsx
- src/app/pages/landing-page.tsx
- src/app/pages/main-page.tsx
- src/app/pages/shared-post-page.tsx
- src/components/Bookmark.tsx
- src/components/NavigationBar.tsx
- src/components/ToggleSwitch.tsx
- src/components/detail-page/CircularProfileImage.tsx
- src/components/detail-page/ImageGrid.tsx
전반적인 수치 단위를 px에서 rem으로 전환하는 작업을 진행했습니다.
그림자 효과, 테두리 두께 등 여러 특이 요소를 제외하고는 모든 부분을 적용하는 것을 목표로 했습니다.
- #13
> fix: px → rem

- src/features/auth/auth.action.ts
- src/shared/persist/index.ts
- src/shared/persist/store.ts
Local, Session Storage Wrapper 함수를 추가하였고, 이를 통해 로그인 상태를 저장하는 코드가 추가되었습니다. 또한, 모든 요청의 헤더에 액세스 토큰을 포함하도록 변경되었습니다.
- #21
> feat: 상태 유지 코드 추가

- src/app/layout.tsx
- src/app/lib/providers/AuthProvider.tsx
- src/app/pages/main-page.tsx
- src/app/pages/shared-post-page.tsx
- src/app/pages/shared-posts.tsx
- src/components/CircularProgressBar.tsx
- src/components/NavigationBar.tsx
- src/components/shared-post-page/MiniCircularProfileImage.tsx
- src/components/shared-posts/SharedPostsFilter.tsx
- src/components/shared-posts/SharedPostsMenu.tsx
- src/entities/user/user.model.ts
- src/features/auth/auth.action.ts
- src/features/auth/auth.hook.ts
인증 상태에 따른 분기 처리 추가 및 특정 액션에 따른 상세 페이지로 라우팅 하도록 기능을 추가하였습니다.
- #34
> feat/fix: 인증 상태에 따른 분기 처리 추가 및 상세 페이지 라우팅

- package-lock.json
- package.json
- src/app/lib/providers/AuthProvider.tsx
- src/app/pages/main-page.tsx
- src/app/pages/shared-posts.tsx
- src/components/NavigationBar.tsx
- src/features/auth/auth.action.ts
- src/features/auth/auth.atom.ts
- src/features/auth/auth.model.ts
- src/shared/persist/effect.ts
- src/shared/persist/index.ts
- src/shared/storage/index.ts
- src/shared/storage/storage.ts
> release:  version 0.3.0

- src/app/layout.tsx
- src/app/lib/providers/AuthProvider.tsx
- src/app/pages/main-page.tsx
- src/app/pages/shared-posts.tsx
- src/components/NavigationBar.tsx
- src/features/auth/auth.action.ts
- src/features/auth/auth.atom.ts
- src/features/auth/auth.model.ts
- src/shared/persist/effect.ts
- src/shared/storage/storage.ts
로그인 상태 유지를 위해 storage 에 따른 상태 유지 코드를 추가했었으나, 작성된 함수는 삭제하지 않지만 사용하지 않기로 결정했습니다.
> fix: 상태 관련 로직 정리

- src/app/pages/profile-page.tsx
birthYear 변수 타입 Date -> number로 변경
> fix: birthDate type Date -> number

- next.config.mjs
- src/app/api/geocode/[query]/route.ts
- src/features/auth/auth.api.ts
- src/features/geocoding/geocoding.api.ts
- src/features/image/image.api.ts
- src/features/profile/profile.api.ts
- src/features/shared/shared.api.ts
보안 문제로, 네이버 API를 이용하려고 할 때, secret value를 숨기기 위해 Next.js의 Route Handler를 사용하도록 수정하였습니다.
- #55
> feat: hide the secret value of the geocoding API 

- package.json
- src/app/layout.tsx
- src/app/lib/providers/ToastProvider.tsx
- src/app/lib/providers/index.ts
- src/app/pages/landing-page.tsx
- src/app/pages/writing-post-page.tsx
- src/features/toast/index.ts
- src/features/toast/toast.atom.ts
- src/features/toast/toast.hook.ts
- src/features/toast/toast.type.ts
- yarn.lock
토스트 메세지 라이브러리를 구현하였습니다. 현재는, 여러 옵션들을 제공하지는 않지만 이후에 추가될 수 있습니다.
- #59
> feat: Implement the toast message library

- src/app/lib/providers/ToastProvider.tsx
토스트 메시지가 여러 개 있을 때 추가와 삭제 애니메이션 효과를 추가했습니다.
- #64
> feat: Enhance the animation effects in the toast message library

- package.json
> release: 0.5.0

- src/app/pages/setting-page.tsx
- src/app/pages/user-input-page.tsx
- src/components/UserInputSection.tsx
- src/components/card/OptionSection.tsx
- src/components/card/VitalSection.tsx
- features form
{features: ["smoking:상관없어요","room:다른 방","mateAge:±6","options:아침형,실내취식 싫어요,상,ISFP,인문,[80,290]"]}
- budget, mbti, major 초기화 하는 useEffect 의존성 배열을 비우면, 초기화가 제대로 이루어지지 않는 경우가 있어서 우선 그대로 둠.
> fix: features form

- public/Close_white.svg
- src/app/pages/profile-page.tsx
- src/features/profile/profile.api.ts
- src/features/profile/profile.dto.ts
- src/features/profile/profile.hook.ts
> feat: apply  certificate

- src/app/chat/page.tsx
- src/app/pages/profile-page.tsx
- src/components/FloatingChatting.tsx
- src/components/NavigationBar.tsx
- src/components/chat/MobileChattingBox.tsx
- src/components/chat/index.ts
> fix: mobile-layout

- src/app/pages/mobile/mobile-shared-post-page.tsx
- src/app/pages/shared-post-page.tsx
- src/components/FloatingChatting.tsx
- src/features/chat/chat.api.ts
- src/features/chat/chat.hook.ts
> feat: Chat-API

- src/components/FloatingChatting.tsx
- src/components/chat/ChattingRoom.tsx
- src/components/chat/MobileChattingBox.tsx
- src/components/chat/MobileChattingRoom.tsx
> feat: Add web socket URL

- src/app/pages/mobile/mobile-shared-post-page.tsx
- src/app/pages/shared-post-page.tsx
- src/app/pages/writing-post-page.tsx
- src/components/FloatingChatting.tsx
- src/components/RangeSlider.tsx
- src/components/chat/ChattingRoom.tsx
- src/components/chat/MobileChattingBox.tsx
- src/components/chat/MobileChattingRoom.tsx
- src/components/shared-posts/filter/DealTypeFilter.tsx
- src/components/shared-posts/filter/RoomTypeFilter.tsx
- src/features/shared/shared.hook.ts
게시글과 관련된 여러 수정 작업
- 게시글 작성시, 내용이 부족하면 작성 불가하게끔 수정
- 게시글 필터링에 필요한 정보 중, 범위로 슬라이더 조작하는 경우 해당 값 가시적으로 표현
- follow, unfollow, scrap 액션들에 대해 데이터 refetch 추가 (데스크탑, 모바일)
> fix: Post pages

- src/app/globals.scss
- src/app/pages/landing-page.tsx
- src/app/pages/main-page.tsx
- src/app/pages/profile-page.tsx
- src/app/pages/shared-posts-page.tsx
- src/app/pages/user-input-page.tsx
- src/components/NavigationBar.tsx
- src/components/shared-posts/SharedPostFilters.tsx
- src/components/shared-posts/SharedPostsMenu.tsx
- src/components/shared-posts/filter/ExtraInfoFilter.tsx
기존 데스크탑 환경 기준 레이아웃을 태블릿 기준으로 변경
> fix: Change the layout from desktop to  tablet

- public/icon-check.svg
- src/app/pages/mobile/mobile-profile-page.tsx
- src/app/pages/mobile/mobile-shared-post-page.tsx
- src/app/pages/mobile/mobile-writing-post-page.tsx
- src/app/pages/profile-page.tsx
- src/app/pages/shared-post-page.tsx
- src/app/pages/writing-post-page.tsx
- src/components/NavigationBar.tsx
- src/components/writing-post-page/MateSearchBox.tsx
- src/features/auth/auth.hook.ts
- src/features/chat/chat.hook.ts
- src/features/profile/profile.api.ts
- src/features/profile/profile.dto.ts
- src/features/profile/profile.hook.ts
- src/features/shared/shared.atom.ts
- src/features/shared/shared.hook.ts
> feat: Add the feature to add mates

- package.json
- src/app/pages/mobile/mobile-shared-post-page.tsx
- src/app/pages/setting-page.tsx
- src/app/pages/shared-post-page.tsx
- src/components/shared-post-page/ImageGrid.tsx
- src/components/shared-posts/SharedPostFilters.tsx
- 게시글에서 메이트 카드 옵션 문제 수정
- 여백 및 일부 디자인 수정
> release: v0.8.1

- src/app/pages/mobile/mobile-profile-page.tsx
- src/app/pages/mobile/mobile-shared-post-page.tsx
- src/app/pages/profile-page.tsx
- src/app/pages/shared-post-page.tsx
- src/components/FloatingChatting.tsx
- src/components/NavigationBar.tsx
- src/components/card/VitalSection.tsx
- src/components/chat/ChatMenu.tsx
- src/components/chat/ChattingRoom.tsx
- src/components/chat/MobileChattingBox.tsx
- src/components/chat/MobileChattingRoom.tsx
- src/features/chat/chat.api.ts
- src/features/chat/chat.hook.ts
- src/features/profile/profile.api.ts
- src/features/profile/profile.dto.ts
- src/features/profile/profile.hook.ts
> feat: 추가 기능 구현

- package.json
> release: v0.9.1

- package.json
- src/app/pages/main-page.tsx
- src/app/pages/mobile/mobile-main-page.tsx
- src/app/pages/shared-posts-page.tsx
- src/components/CircularProfileImage.tsx
- src/components/main-page/UserCard.tsx
> release: v0.10.0

- .eslintrc.json
- src/app/pages/main-page.tsx
- src/app/pages/mobile/mobile-main-page.tsx
- src/components/main-page/UserCard.tsx
- 주변에 있는 추천 유저를 지도에 표시
- 유저 카드 특성 추가
- #104
> feat: Add recommended user-marker

- .eslintrc.json
- package.json
- src/app/not-found.tsx
- src/app/pages/main-page.tsx
- src/app/pages/mobile/mobile-main-page.tsx
- src/app/pages/mobile/mobile-profile-page.tsx
- src/app/pages/mobile/mobile-shared-posts-page.tsx
- src/app/pages/profile-page.tsx
- src/app/pages/shared-post-page.tsx
- src/app/pages/shared-posts-page.tsx
- src/components/CircularProfileImage.tsx
- src/components/main-page/UserCard.tsx
- yarn.lock
- 주변 추천 유저 마커 추가
- 유저 카드 특성 추가 및 변경
- 404 페이지 Next.js 라우터 규칙에 따르게 수정
- Atom key가 중복되는 문제 핸들러 이용하는 방식으로 해결
- #100 
- #103 
- #104
closes #100, #103 , #104
> release: v0.11.1
